import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gambetta = localFont({src: './fonts/Gambetta-Variable.woff', variable: '--font-gambetta', weight: '100 900'});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`bg-black text-amber-50 ${gambetta.className}`}>
        {children}
      </body>
    </html>
  );
}
